# fly.toml app configuration file generated for altscore-challenge-7 on 2024-10-27T01:44:31-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "altscore-challenge-7"
primary_region = "ord"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
